[tool.poetry]
name = "poc-spacy"
version = "0.1.0"
description = ""
authors = ["Justal Kevin <justal.kevin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spacy = "^3.7.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
